### ISSUE TITLE
No such container: anvil

### ISSUE THREAD

**Issue by lyledavids** [Layr-Labs/hello-world-avs#29]
When following steps provided. I get this error message after running the make start-chain-with-contracts-deployed command

![Screenshot 2024-07-01 at 12 56 35](https://github.com/Layr-Labs/hello-world-avs/assets/14069492/fc9b0b0a-bd3d-46c9-a593-38a9276b97a4)

**Comment by wawrzek** [comment]
If you read the error message carefully, the issue is with the volume name. The volume path looks wrong.

**Comment by lyledavids** [comment]
@wawrzek what must the volume name be?

**Comment by wawrzek** [comment]
On the screenshot, it looks like the first path points at a directory (Desktop/Hackaton), not a file.
