### ISSUE TITLE
index.ts registerOperatorWithSignature outdated 

### ISSUE THREAD

**Issue by ryjiangx** [Layr-Labs/hello-world-avs#39]
In the `registerOperator` function within `operator/index.ts` of the `hello-world-avs` template, `registerOperatorWithSignature(address, signature)` is called using an outdated ABI. This does not match the `registerOperatorWithSignature(signature, address)` in `unaudited/ECDSAStakeRegistry.sol`.

Please update the index.ts code in hello-world-avs and the corresponding ABI to facilitate future development.

**Comment by wesfloyd** [comment]
Thank you for reporting this! I'm struggling with resolving a similar breaking point in the code.

Can you clarify where you confirmed the ABI is outdated? Eg [per here](https://github.com/Layr-Labs/eigenlayer-middleware/blob/7d49b5181b09198ed275783453aa082bb3766990/src/unaudited/ECDSAStakeRegistry.sol#L48) the signature does not appear to have changed.

**Comment by dabit3** [comment]
Thanks @ryjiangx this should be fixed now
