### ISSUE TITLE
Add new strategy tutorial issue

### ISSUE THREAD

**Issue by claudiovb** [Layr-Labs/hello-world-avs#53]
I'm having some trouble with the following piece of AddNewStrategy file:
https://github.com/Layr-Labs/hello-world-avs/blob/f48f498a52d3a2c8c2386e0f1cd9fb47340b49bc/contracts/script/AddNewStrategy.s.sol#L96
there it tries to reinitialize the stakeRegistryProxy what is not permitted as initializer code can run only once, tried to look for alternatives but the only way to add a new quorum by other means involves passing the operators as long, what I'm missing here ?

**Comment by wesfloyd** [comment]
Hi @Gajesh2007 - let me know if you have time to investigate? Otherwise I can make time this week to review

**Comment by wesfloyd** [comment]
Hi @claudiovb thank you for raising this issue. I can confirm that there are multiple issues and outdated libraries with the current master branch. We are close to merging in many fixes to the mainline codebase via these PRs:
https://github.com/Layr-Labs/hello-world-avs/pull/57
https://github.com/Layr-Labs/hello-world-avs/pull/58

If you can bear with us for another few days, we'll have it cleaned up for you and we can retest 👍
