### ISSUE TITLE
fix typo in package.json

### ISSUE THREAD

**Issue by kayvank** [Layr-Labs/hello-world-avs#73]
**Ask**
Fix the typo in the package.json regarding the file name.
The fix is required for the following instruction to work correctly in Linux platforms where filenames are case-sensitive
```
npm run deploy:core
```

**Detail**
```
npm run deploy:core
``` 
are erroring out in *nix. The Reason is a small typo in the file [name](https://github.com/Layr-Labs/hello-world-avs/blob/master/package.json#L9). 
The fix is:
`DeployEigenlayerCore.s.sol` should be changed to `DeployEigenLayerCore.s.sol`
The same change should be applied to `deploy:core-debug` on [line 11](https://github.com/Layr-Labs/hello-world-avs/blob/master/package.json#L11)

**Comment by kayvank** [comment]
Small [PR-72](https://github.com/Layr-Labs/hello-world-avs/pull/72) should fix the issue.

**Comment by stevennevins** [comment]
Thanks for the report and the [PR](https://github.com/Layr-Labs/hello-world-avs/pull/72)
